cronbot:
  security:
    jwt:
      access-token-validity: 30
    new-user-default-password: 123456789

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
  main:
    allow-bean-definition-overriding: true